-- Create table for Mercadolibre notifications
CREATE TABLE IF NOT EXISTS public.mercadolibre_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource text NOT NULL,
    user_id bigint NOT NULL,
    topic text NOT NULL,
    application_id bigint NOT NULL,
    attempts int NOT NULL DEFAULT 1,
    sent timestamptz NOT NULL DEFAULT now(),
    received timestamptz NOT NULL DEFAULT now(),
    status text NOT NULL DEFAULT 'pending',
    raw_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    processed_at timestamptz NULL
);

-- Add comment to table
COMMENT ON TABLE public.mercadolibre_notifications IS 'Stores notifications from Mercado Libre webhooks';

-- Create index on topic for faster filtering
CREATE INDEX IF NOT EXISTS mercadolibre_notifications_topic_idx ON public.mercadolibre_notifications(topic);

-- Create index on status for faster filtering
CREATE INDEX IF NOT EXISTS mercadolibre_notifications_status_idx ON public.mercadolibre_notifications(status);

-- Set up Row Level Security (RLS)
ALTER TABLE public.mercadolibre_notifications ENABLE ROW LEVEL SECURITY;

-- Grant access to authenticated users
GRANT ALL ON public.mercadolibre_notifications TO authenticated;

-- Create policy to allow insert for service role
CREATE POLICY "Allow service role to insert notifications"
  ON public.mercadolibre_notifications
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Create policy to allow select for service role
CREATE POLICY "Allow service role to select notifications"
  ON public.mercadolibre_notifications
  FOR SELECT
  TO authenticated
  USING (true);

-- Create policy to allow update for service role
CREATE POLICY "Allow service role to update notifications"
  ON public.mercadolibre_notifications
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true); 